name: 233BedWars
author: SerendipityR
version: 1.0.0
softdepend: [BedWars1058, TheAPI, PlaceholderAPI]
main: cn.serendipityr._233bedwars._233BedWars
permissions:
  bw233.cmd:
    default: true
commands:
  233bw:
    permission: bw233.cmd
  233bedwars:
    permission: bw233.cmd