name: 233BedWars
author: SerendipityR
version: 1.0.3_hotfix
softdepend: [BedWars1058, PlaceholderAPI]
main: cn.serendipityr._233bedwars._233BedWars
permissions:
  bw233.cmd:
    default: true
  bw233.admin:
    default: op
commands:
  233bw:
    permission: bw233.cmd
  233bedwars:
    permission: bw233.cmd